
version: "3.9"

services:
  db:
    image: ${PSTGRES_DOCKER_COMPOSE_VARIABLE}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB:${PSTGRES_DOCKER_COMPOSE_VARIABLE}
      - POSTGRES_USER:${PSTGRES_DOCKER_COMPOSE_VARIABLE}
      - POSTGRES_PASSWORD:${PSTGRES_DOCKER_COMPOSE_VARIABLE}
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME:${PSTGRES_DOCKER_COMPOSE_VARIABLE}
      - POSTGRES_USER:${PSTGRES_DOCKER_COMPOSE_VARIABLE}
      - POSTGRES_PASSWORD:${PSTGRES_DOCKER_COMPOSE_VARIABLE}
    depends_on:
      - db