# Generated by Django 4.0.4 on 2022-05-10 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_ticket_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='category',
        ),
        migrations.AddField(
            model_name='ticket',
            name='cats',
            field=models.ForeignKey(default='Active', on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
