# Generated by Django 4.0.4 on 2022-05-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_ticket_category_ticket_cats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='cats',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(blank=True, default='Active'),
        ),
    ]
